In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Store filepath in a variable
df = pd.read_excel('HomicideData.xlsx')
print(df)

                       Weapons   2014   2015   2016   2017   2018
0                        Total  12278  13780  15318  15195  14123
1               Total_firearms   7803   9103  10372  11006  10265
2                     Handguns   5342   6176   6762   7051   6603
3                       Rifles    235    215    300    390    297
4                     Shotguns    238    247    247    264    235
5                   Other guns     88    151    172    180    167
6          Firearms_not_stated   1900   2314   2891   3121   2963
7   Knives/cutting_instruments   1545   1525   1558   1609   1515
8                Blunt_objects    431    436    464    472    443
9            Personal_weapons     668    647    664    710    672
10                      Poison      9      8     12     15      5
11                  Explosives      6      1      1      0      4
12                        Fire     55     63     78     96     72
13                   Narcotics     70     69    118    110     78
14                    Drowning     12     12      9      8      9
15               Strangulation     84     96     97     89     70
16                Asphyxiation     93    105     92    111     90
17               Other_weapons   1502   1715   1853    969    900

In [3]:
# trump 2017 data

df1 = pd.read_excel('Trump_2017.xlsx')
print(df1)

                State  Total_murders  Total_firearms  Handguns  Rifles  \
0             Alabama              2               1         0       0
1              Alaska             62              37         7       3
2             Arizona            404             249       162       8
3            Arkansas            250             168        92      11
4          California           1830            1274       886      37
5            Colorado            218             137        88       7
6         Connecticut            102              72        30       0
7            Delaware             52              44        20       0
8   District_Columbia            116              90        89       0
9             Georgia            672             542       490      15
10             Hawaii             39               4         1       1
11              Idaho             28              13         8       4
12           Illinois            814             693       596      24
13            Indiana            360             291       147      14
14               Iowa            100              57        25       1
15             Kansas            129              79        44       4
16           Kentucky            263             192       128       6
17          Louisiana            566             460       216      23
18              Maine             23              12         4       0
19           Maryland            475             370       339       5
20      Massachusetts            170              99        34       0
21           Michigan            567             381       185      13
22          Minnesota            113              69        58       1
23        Mississippi            149             111        90       4
24           Missouri            596             514       224      22
25            Montana             41              17        10       2
26           Nebraska             43              31        27       2
27             Nevada            270             201        16      58
28      New_Hampshire             14               7         4       0
29         New_Jersey            324             242       175       7
30         New_Mexico            113              71        20       2
31           New_York            547             292       233       6
32     North_Carolina            547             413       279       9
33       North_Dakota              9               5         2       1
34               Ohio            682             485       226       5
35           Oklahoma            239             163       131       5
36             Oregon            100              58        34       2
37       Pennsylvania            735             567       452      11
38       Rhode_Island             20               8         1       0
39     South_Carolina            387             312       183      11
40       South_Dakota             21               8         6       0
41          Tennessee            525             407       271      19
42              Texas           1364            1012       594      40
43               Utah             73              46        32       0
44            Vermont             14               6         1       0
45           Virginia            453             338       156      11
46         Washington            228             134        75       1
47      West Virginia             79              45        25       4
48          Wisconsin            186             149       111       4
49            Wyoming             14               6         5       0
50               Guam              1               0         0       0

    Shotguns  Firearms_unknown  Knives_cutting_instruments  Other_weapons  \
0          0                 1                           0              1
1          3                24                          13              8
2          9                70                          50             93
3          4                61                          23             52
4         34               317                         258            195
5          4                38                          37             22
6          1                41                          11              9
7          1                23                           3              4
8          0                 1                          15              5
9          5                32                          37             85
10         0                 2                           9             10
11         1                 0                           6              3
12         3                70                          53             50
13         6               124                          20             39
14         5                26                          18             18
15         7                24                          16             26
16         6                52                          25             33
17        12               209                          46             42
18         0                 8                           3              4
19         3                23                          44             50
20         0                65                          36             29
21        12               171                          55            101
22         2                 8                          14             23
23         3                14                          12             20
24         8               260                          25             48
25         1                 4                          12              5
26         2                 0                           4              5
27         0               127                          28             30
28         1                 2                           5              1
29         4                56                          42             29
30         0                49                          20             19
31         9                44                         113             91
32        26                99                          33             64
33         0                 2                           1              2
34        11               243                          46            128
35         5                22                          25             32
36         2                20                          17             22
37         8                96                          63             73
38         0                 7                           4              5
39         8               110                          29             36
40         0                 2                           7              2
41        11               106                          42             64
42        26               352                         156            131
43         3                11                           7             12
44         0                 5                           6              1
45        11               160                          44             54
46         1                57                          36             40
47         4                12                           8             23
48         2                32                          11             17
49         0                 1                           3              3
50         0                 0                           0              1

    Hands_fists_feet_etc
0                      0
1                      4
2                     12
3                      7
4                    103
5                     22
6                     10
7                      1
8                      6
9                      8
10                    16
11                     6
12                    18
13                    10
14                     7
15                     8
16                    13
17                    18
18                     4
19                    11
20                     6
21                    30
22                     7
23                     6
24                     9
25                     7
26                     3
27                    11
28                     1
29                    11
30                     3
31                    51
32                    37
33                     1
34                    23
35                    19
36                     3
37                    32
38                     3
39                    10
40                     4
41                    12
42                    65
43                     8
44                     1
45                    17
46                    18
47                     3
48                     9
49                     2
50                     0